import { Settings } from "./types";

export const defaultConfig: Settings = {
  streamerBotWebsocketUrl: "ws://localhost:8080/",
  overlayServerPort: 3030,
  twitchUsername: "",
  enableAllAnimations: true,
  enableAllFeatures: true,
  features: {
    lurk: { enabled: true },
    welcome: { enabled: true },
    kappagen: { enabled: true },
    cheers: { enabled: true },
    hypetrain: { enabled: true },
    emoterain: { enabled: true },
    choon: { enabled: true },
  },
  animations: {
    rain: { enabled: true },
    rise: { enabled: true },
    explode: { enabled: true },
    volcano: { enabled: true },
    firework: { enabled: true },
    rightwave: { enabled: true },
    leftwave: { enabled: true },
    carousel: { enabled: true },
    spiral: { enabled: true },
    comets: { enabled: true },
    dvd: { enabled: true },
    text: { enabled: true },
    cyclone: { enabled: true },
    tetris: { enabled: true },
    bounce: { enabled: true },
    cube: { enabled: true },
    fade: { enabled: true },
    dodecahedron: { enabled: true },
    traffic: { enabled: true },
    snake: { enabled: true },
    solitaire: { enabled: true },
  },
  maxEmotes: 200,
  subOnly: false,
  defaultEmotes: 100,
  debug: false,
  configFilePath: "",
};
